version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672"  # Porta para conexão com o RabbitMQ
      - "15672:15672"  # Porta para acessar a interface de gerenciamento do RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest