# Generated by Django 4.2.2 on 2023-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sector",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
