# Generated by Django 4.2.2 on 2023-06-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sector",
        ),
        migrations.AddField(
            model_name="project",
            name="template_type",
            field=models.CharField(
                blank=True,
                choices=[("support", "Support"), ("lead_capture:chat_gpt", "Chat GPT")],
                max_length=100,
                null=True,
            ),
        ),
    ]
